name: snowrun_app
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+000001

# fvm flutter clean && fvm flutter packages pub get && fvm flutter packages pub run build_runner build --delete-conflicting-outputs
# fvm flutter packages pub run build_runner watch --delete-conflicting-outputs

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0

  mapbox_maps_flutter: ^0.4.5
  geolocator: ^9.0.2
  google_sign_in: ^6.1.5
  http: ^1.1.0

  firebase_core: ^2.17.0
  firebase_auth: ^4.7.2
  firebase_crashlytics: ^3.3.7
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1
  firebase_performance: ^0.9.2+7

  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0

  injectable: ^2.1.2
  get_it: ^7.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1

  version: ^3.0.2

  intl: ^0.18.1
  fluttertoast: ^8.2.2
  app_settings: ^5.0.0
  flutter_blurhash: ^0.7.0

  lottie: ^2.6.0
  flutter_native_splash: ^2.3.2
  animate_do: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/app_icon_1024.png"
  icon_adaptive_foreground: "assets/icon/app_icon_1024.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/png/
    - assets/webp/
    - assets/webp/2x/
    - assets/webp/3x/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Bold.otf
        - asset: assets/font/Pretendard-Regular.otf
          weight: 700